#!/bin/bash
ls -la        # List files in the current directory (including hidden files)
ls -la ..      # List files in the parent directory (including hidden files)
ls -la /boot   # List files in the /boot directory (including hidden files)
